### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by axierjhtjz** [mg6maciej/android-maps-extensions#23]
Is there a way to stop using the external storage? For example, when the apps asks for ```<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>```the Google Play Store filters all the Nexus 7 Devices.

Thanks in advance.

**Comment by mg6maciej** [comment]
This is a question to Google Maps Android API v2 creators. This library is using official maps lib and doesn't require any additional permissions.

**Comment by axierjhtjz** [comment]
It´s true, mixed it with another issue on my app. Sorry for that.
