### ISSUE TITLE
Tombstoned clusters

### ISSUE THREAD

**Issue by daveeeh** [mg6maciej/android-maps-extensions#24]
Great library, much quicker than the Google one.

Slight problem though - I'm adding ~16,000 markers relatively slowly while moving around the map, zooming etc.

After not very long some of the clusters will remain with a very high number of markers but zooming in all the way it will stay the same.  If I tap one of these clusters it fires the method to get the info window:
public View getInfoContents(Marker marker) {}

However the marker that is passed is null.

At the very least is there a way to force the map to re-group all the markers to remove these wrong ones?

David

**Comment by mg6maciej** [comment]
Hey David,
This sounds like a bug and it should not happen. Can you provide simple, self-contained example showing this issue, so we can figure out if it's a bug in the library or your code?

**Comment by daveeeh** [comment]
OK, I'll try and do that.

**Comment by askarsyzdykov** [comment]
Hi,
I also have this problem. 
1. Add 100 markers nearby.
2. add more markers (nearby) away from rest of 100 markers
3. Increase / decrease zoom

**Comment by mg6maciej** [comment]
Thanks for detailed steps to reproduce this issue. Could you also share the code? Can be here in comments or in a gist.

**Comment by askarsyzdykov** [comment]
https://gist.github.com/askarsyzdykov/8e4a00d4bcddd051318c

**Comment by mg6maciej** [comment]
@askarsyzdykov Thanks for the snippet, but I was hoping more for a list of places that's missing to run and reproduce the issue.
