### ISSUE TITLE
Using of onclusterClickListener 

### ISSUE THREAD

**Issue by colonelka** [mg6maciej/android-maps-extensions#25]
how can I use onClusterClickListener which exist in google maps what is the way to use it with your library

**Comment by mg6maciej** [comment]
What do you mean by `onClusterClickListener`? There is no such listener in Google Maps Android API v2. If you mean Google Maps Utils, these libraries won't work together if you want to do clustering in both.  
In Android Maps Extensions, you just add `OnMarkerClickListener` and can check if clicked marker is a cluster or not via `Marker.isCluster()`.

**Comment by colonelka** [comment]
thank you a lot for your quick response yes indeed this is what I mean
