### ISSUE TITLE
Touchable map

### ISSUE THREAD

**Issue by Paroca72** [mg6maciej/android-maps-extensions#27]
Great Work man!!!

Im working with SupportMapFragment.
It is possibible to implement a touchable map?

onTouch()
onRelease()

Thanks
Sam

**Comment by jnsone11** [comment]
This is what I did..


import android.content.Context;
import android.os.Handler;
import android.os.Message;
import android.util.AttributeSet;
import android.util.Log;
import android.view.GestureDetector;
import android.view.MotionEvent;

import com.androidmapsextensions.MapView;
import com.google.android.gms.maps.GoogleMapOptions;


/**
 * Created by jns111 on 01/05/15.
 */
public class TouchableMapView extends MapView {

    MapViewTochListener mapViewTochListener;
    GestureDetector tapListener;
    GestureDetector scrollListener;
    GestureDetector doubleTabListener;

    public TouchableMapView(Context context) {
        super(context);
        init();
    }

    public TouchableMapView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    public TouchableMapView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init();
    }

    public TouchableMapView(Context context, GoogleMapOptions options) {
        super(context, options);
        init();
    }

    private void init() {
        tapListener = new GestureDetector(getContext(), new GestureDetector.SimpleOnGestureListener() {

            @Override
            public boolean onSingleTapUp(MotionEvent e) {
                return true;
            }
        });

        scrollListener = new GestureDetector(getContext(), new GestureDetector.SimpleOnGestureListener() {
            @Override
            public boolean onScroll(MotionEvent e1, MotionEvent e2, float distanceX, float distanceY) {
                return true;
            }
        });
        doubleTabListener = new GestureDetector(getContext(),new GestureDetector.SimpleOnGestureListener(){
            @Override
            public boolean onDoubleTap(MotionEvent e) {
                return true;
            }
        });
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {

        if (mapViewTochListener != null) {
            if (tapListener.onTouchEvent(ev)) {
                singleTapHandler.removeMessages(MESSAGE_ONSINGLETAP);
                singleTapHandler.sendMessageDelayed(singleTapHandler.obtainMessage(MESSAGE_ONSINGLETAP),SINGLETAP_DELAY);
            } else if (scrollListener.onTouchEvent(ev)) {
                mapViewTochListener.onScroll();
            }

            if (doubleTabListener.onTouchEvent(ev)){
                singleTapHandler.removeMessages(MESSAGE_ONSINGLETAP);
                mapViewTochListener.onDoubleTap();
            }
        }

        return super.onInterceptTouchEvent(ev);
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {

        Log.w("MAP","onTouchEvent: "+event.toString());

        return super.onTouchEvent(event);
    }

    public void setOnMapViewTouchListener(MapViewTochListener listener) {
        mapViewTochListener = listener;
    }

    public interface MapViewTochListener {
        void onSingleTapUp();
        void onDoubleTap();
        void onScroll();
    }

    private final static int MESSAGE_ONSINGLETAP = 1337;
    private final static int SINGLETAP_DELAY = 200;

    private final Handler singleTapHandler = new Handler(new Handler.Callback() {
        @Override
        public boolean handleMessage(Message msg) {
            mapViewTochListener.onSingleTapUp();
            return true;
        }
    });
}

**Comment by Paroca72** [comment]
Very thanks.. i will try soon
