### ISSUE TITLE
update to most recent Google-play-service 7.8.0

### ISSUE THREAD

**Issue by hannesa2** [mg6maciej/android-maps-extensions#29]
Is there any plan to upgrade to most recent Google-play-service 7.8.0 ?

    compile 'com.google.android.gms:play-services:7.8.0'

Doing this step for gradle build and update to most recent build-tools as well to 

    classpath 'com.android.tools.build:gradle:1.3.0'

I see the minSdkVersion is updated in build.gradle. Ok it's for Eclipse, but why ?
It has no influence to gradle build, but it runs into an issue, because processManifest was removed by 1.0

    variant.processManifest.doFirst

so I can't make a PR.
Honestly, I would completely remove this task

**Comment by mg6maciej** [comment]
I'm not sure where is the problem. `variant.processManifest.doFirst` doesn't exist in the current code base (develop or master branch). It was added in https://github.com/mg6maciej/android-maps-extensions/commit/465595525a138e0d738b6818eafbca9599f5bf19, changed a few times and later removed in https://github.com/mg6maciej/android-maps-extensions/commit/ef88663a30292f6942295e9361b5e190cffdc87e. `<uses-sdk tools:overrideLibrary="..." />` in AndroidManifest does the same job.

There is no need to recompile AME with the newest version of Google Play Services to be able to use it, so if you want to use AME with newer version of Google Play Services, you are free to do that (I'm currently using AME with GPServices 7.5.0). Unless there are some new features you would like to use (i.e. methods added to public classes in maps API), you are good to go and set any Google Play Services version (starting from 3.2.65) you wish in your project. Just note that when you use older version of Google Play Services and want to call some newer API, it will crash somewhere.

**Comment by hannesa2** [comment]
sorry, gradle issues were still present in my fork
