### ISSUE TITLE
Cannot set marker data

### ISSUE THREAD

**Issue by paulcanning** [mg6maciej/android-maps-extensions#30]
For the life of me, I am unable to figure out how to use setData() for a Marker.

My code:

    MarkerOptions markerOptions = new MarkerOptions().position(position).title(title).snippet(snippet);

    Marker marker = map.addMarker(markerOptions);

    marker.setData(data); // This doens't work, simply says cannot resolve.

I have the following in my build.gradle:

    compile 'com.androidmapsextensions:android-maps-extensions:2.2.0'
    compile 'com.google.android.gms:play-services-maps:7.8.0'
    compile 'com.google.android.gms:play-services-location:7.8.0'

How the heck do I use setData?!

**Comment by mg6maciej** [comment]
Most probably you have incorrect imports.
You need to import classes like `GoogleMap`, `MarkerOptions and `Marker` from `com.androidmapsextensions` package.
After you do that you will also have `MarkerOptions::data` method, where you can set data during marker creation.
Let me know if this helps you.
