### ISSUE TITLE
exclude some marker from clustering

### ISSUE THREAD

**Issue by hannesa2** [mg6maciej/android-maps-extensions#31]
I have some markers, which i I want always see, interdependent of zoom level.
One approach could be to have two ClusterManagers like map-utils have,
or to exclude it from clustering.

Is there a way to solve this with AME ?

AME is a cool lib, it's really fast for huge amount of markers !

**Comment by mg6maciej** [comment]
In AME this concept is called grouping. You may create markers that are not grouped with others by putting them into separate groups. The default group is 0 if not set explicitly.

* `new MarkerOptions().clusterGroup(1)` on a few markers to have them cluster with each other, but not with all the others or
* `new MarkerOptions().clusterGroup(CusterGroup.NOT_CLUSTERED)` to have your markers never join any cluster

You may also change cluster group of any single marker by calling `Marker.setClusterGroup` and it will immediately update how markers are clustered together.
