### ISSUE TITLE
allow animation of alpha

### ISSUE THREAD

**Issue by dbachelder** [mg6maciej/android-maps-extensions#32]
our markers change around quite a bit while the user zooms and pans, it looks nicer if they fade in and out, but it can be tricky to manage as a marker can get .remove()'ed between frames, then setAlpha() results in a NPE. 

I think if I could get a handle on the underlying google marker object for animation purposes I could mitigate this problem. 

Additionally, .setAlpha (and other methods in lazymarker) should probably do null checks on both marker and markerOptions to prevent NPEs when referencing "stale" marker references.

**Comment by mg6maciej** [comment]
Hello Dan,

Let me start with describing my perspective shortly. When an (unexpected) exception is thrown, that means a user (i.e. developer) did something wrong, or that there is a bug in given library, or both. And the best thing that can happen to developer is stopping the execution of a program, so they can fix the issue. Trying to hide the issue by doing nothing may only cause problems like memory leaks and crashes later in time for no apparent reason.
In this case you are describing, you are trying to use a `Marker` object that had its `remove` method called. For me this is like trying to use `InputStream` after calling `close`. After calling `remove` (or `close`) you should stop referencing such objects, as they are really of no use and can be GCed.

That being said, some hints on how you can continue from where you are:
* Just grab the code and make things you want `public` public. I did this with my own library and I know other people did it too, using AME just as a base for what they need. License is dev friendly after all.
* If you want to have a non-crashing alpha animation, I would suggest looking at `Marker::animatePosition` and all the way down to `MarkerAnimator`. That code is similar to what you try to achieve with alpha, just works on `LatLng`. It has proper handling of marker removal and also things like calling `setPosition` or `animatePosition` again during animation. Also if you want to make a contribution, I would be glad to accept pull request with `Marker::animateAlpha` implementation similar to my old code.

Let me know if it helps a bit.

**Comment by dbachelder** [comment]
Thanks. I have temporarily fixed our problems by removing the animations and forking the project and adding some synchronization to the markermanager. Which prevents concurrent modification exceptions while adding markers on the main thread and iterating the markers on another thread. Would you be interested in adding that to the project?

**Comment by mg6maciej** [comment]
Hey, I have looked into the changes you made. For the library it makes no sense, because Google Maps Android API v2 requires its methods to be called from main thread (unless something changed in some recent version). I would have to see some snippets of your code to understand why you want or need to call some method from other thread. I assume this is `GoogleMap::getMarkers`, or `getDisplayedMarkers`.
