### ISSUE TITLE
Q: Check if a marker already exists

### ISSUE THREAD

**Issue by brunano21** [mg6maciej/android-maps-extensions#33]
Hello

I'm adding markers to the map at every response by Google Places service. However, I would like to check if a marker with a given position (lat, lng) is already added to map. If not, I'll add it, otherwise I'll skip the operation.
So, I wonder if there is any fast check to accomplish that. 
Thanks!

**Comment by black-snow** [comment]
Guess you'll have to loop through all markers and check their positions.
Alternatively store all your markers in a tree (or some other structure) and look up there.

**Comment by mg6maciej** [comment]
Yes, you could normally loop through them, but if you have a lot of markers and want such operation to be faster, I suggest using some kind of map structure with lat/lng as keys. Note however this bug: https://code.google.com/p/gmaps-api-issues/issues/detail?id=5353

**Comment by black-snow** [comment]
Yup, you should write your own little comparator for coordinates (with configurable resolution maybe).
