### ISSUE TITLE
Thank you - great work

### ISSUE THREAD

**Issue by MSIH** [mg6maciej/android-maps-extensions#43]
I just wanted to thank you for making a great library.

**Comment by mg6maciej** [comment]
Thank you. Happy New Year!

**Comment by albertosarullo** [comment]
Thank you from Italy!

**Comment by mg6maciej** [comment]
Thanks again. I just updated AME to 2.4.0 to match the latest circle/polygon/polyline styling stuff from Google Maps API. See you in Turin 🇮🇹.

**Comment by albertosarullo** [comment]
Great! :)

Alberto
