### ISSUE TITLE
Build APK not generate APK

### ISSUE THREAD

**Issue by albertosarullo** [mg6maciej/android-maps-extensions#46]
I download the version 2.4.0. The demo is working great on emulator, but is impossible to run on device. 

When i Build APK in Android Studio (v2.3, OSX), I get the message "APK(s) generated successfully.", but the build/outputs/ folder contains only 2 .aar files (android-maps-extensions-debug.aar, android-maps-extensions-release.aar).

I have successfully installed on device other applications via adb, so I think is not a device dependent problem.

**Comment by mg6maciej** [comment]
Works for me.

<img width="481" alt="screen shot 2017-03-12 at 14 20 21" src="https://cloud.githubusercontent.com/assets/1316369/23832179/1c3c7756-0730-11e7-8373-5ffe52169676.png">

**Comment by albertosarullo** [comment]
It is my fault (an app has modified an environment variable), sorry
