### ISSUE TITLE
Exception is thrown if getExtendedMap is called

### ISSUE THREAD

**Issue by zeray01** [mg6maciej/android-maps-extensions#53]
Hi, 
i inherited an older project, that uses your library and after updating the "play-services-maps" to 11.2.0, i always get a "java.lang.RuntimeException: java.lang.NoSuchMethodException: getMap []" Exception. I also tried to use version 10.2.0 like you say in your description, but the result is the same. 
I cannot downgrade too much, because i need the newer versions of the libraries in other parts of the project.
The version of your library, that i use is 2.4.0.
Do you perhaps have any idea, what the problem could be?

**Comment by mg6maciej** [comment]
The issue is Google removed `getMap` from their API at some point, so you need to use `getExtendedMapAsync`, which calls `getMapAsync` instead when using newer versions of GPServices. Let me know if you have any problems there.

**Comment by mg6maciej** [comment]
https://github.com/mg6maciej/android-maps-extensions/commit/f9a733b5f3efc9f85f39d8db24dd3acc269d702b

**Comment by zeray01** [comment]
Thank you, that helped a lot!
