### ISSUE TITLE
GeoJson Feature Request?

### ISSUE THREAD

**Issue by jasonflaherty** [mg6maciej/android-maps-extensions#56]
Your clustering engine is soooo much more efficient IMO than the google utilities. I was working on a project that needed a geojson overlay and noticed that this wonderful library doesn't have that baked in. Is this something that is being looked at for a future release? I can explore other options for GeoJson polygons if not. Thanks!

**Comment by mg6maciej** [comment]
Hello Jason,

Glad you like how this lib works.

I noticed there is `GeoJsonLayer` in android-maps-utils from Google. Sadly it's not part of the Google Maps Android API, so there is not much I can do to support that implementation. And I'd rather not re-implement the wheel.

If you don't mind having both AME and utils dependencies, you may hack this library code a bit to expose `com.google...GoogleMap` by adding something like `getOriginalMap()` to `com.androidmapsextensions.GoogleMap` and implementing it with simple `return real.getMap();` in `.impl.DelegatingGoogleMap`.
If you do, you will be able to use it with `new GeoJsonLayer(map.getOriginalMap(), ...)`.

Cheers & Merry,
Maciej

**Comment by jasonflaherty** [comment]
Thanks for the Reply. I'll see if my skills are up for that. I don't mind loading both libraries. I actually tried doing it to no avail due to this exact reason. Merry Christmas too you!
