### ISSUE TITLE
MarkerCLuster using svg image 

### ISSUE THREAD

**Issue by tushars-arrk** [mg6maciej/android-maps-extensions#58]
Hi maciej,

can i used svg image instead of bitmap for cluster icon. i did same for map pins using below code 

public static BitmapDescriptor bitmapDescriptorFromVector(Context context, int vectorResId) {
        Drawable vectorDrawable = ContextCompat.getDrawable(context, vectorResId);
        vectorDrawable.setBounds(0, 0, vectorDrawable.getIntrinsicWidth(), vectorDrawable.getIntrinsicHeight());
        Bitmap bitmap = Bitmap.createBitmap(vectorDrawable.getIntrinsicWidth(), vectorDrawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        vectorDrawable.draw(canvas);
        return BitmapDescriptorFactory.fromBitmap(bitmap);
    }

**Comment by mg6maciej** [comment]
You may do so by creating your own [`ClusterOptionsProvider`](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions/src/main/java/com/androidmapsextensions/ClusterOptionsProvider.java) implementation.
There is the default one in the library [here](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions/src/main/java/com/androidmapsextensions/DefaultClusterOptionsProvider.java) and there is one in demo [here](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions-demo/src/main/java/pl/mg6/android/maps/extensions/demo/DemoClusterOptionsProvider.java) as examples. And this is how you change it: [`DeclusterificationExampleFragment` line 46](https://github.com/mg6maciej/android-maps-extensions/blob/develop/android-maps-extensions-demo/src/main/java/pl/mg6/android/maps/extensions/demo/DeclusterificationExampleFragment.java#L46).
