### ISSUE TITLE
Project dead ? RIP

### ISSUE THREAD

**Issue by hannesa2** [mg6maciej/android-maps-extensions#70]
It looks like the maintainer has lost his interest at all, because all my pull requests are unmerged.

But helping myself, I made my [fork](https://github.com/hannesa2/android-maps-extensions?organization=hannesa2&organization=hannesa2) up do date.

It contains Android X, most recent build tools Android Studio 3.5 and several additional improvements.

You can use it with 
```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

```
dependencies {
    implementation 'com.github.hannesa2:android-maps-extensions:$latest'
}
```

**Comment by Testator** [comment]
> It looks like the maintainer has lost his interest at all, because all my pull requests are unmerged.
> 
> But helping myself, I made my [fork](https://github.com/hannesa2/android-maps-extensions?organization=hannesa2&organization=hannesa2) up do date.
> 
> It contains Android X, most recent build tools Android Studio 3.5 and several additional improvements.
> 
> You can use it with
> 
> ```
> allprojects {
> 	repositories {
> 		...
> 		maven { url 'https://jitpack.io' }
> 	}
> }
> ```
> 
> ```
> dependencies {
>     implementation 'com.github.hannesa2:android-maps-extensions:$latest'
> }
> ```

yeah but what is the latest version? you can't just make stuff and don't explain.. don't you hate others that are incomplete in their examples?

**Comment by hannesa2** [comment]
Take it form here

<img width="443" alt="image" src="https://user-images.githubusercontent.com/3314607/83963323-78eba200-a8a5-11ea-86ce-6255868701cb.png">

or from else where.
My fork has

<img width="420" alt="image" src="https://user-images.githubusercontent.com/3314607/83963311-5c4f6a00-a8a5-11ea-9d78-e32b3f8103ee.png">

**Comment by hannesa2** [comment]
> don't you hate others that are incomplete in their examples?

Speaking about hate is very strong. You can help everybody, if you don't like current situation

**Comment by Testator** [comment]
exactly!  first of all Jitpack 3.0 is a not a version # ! You are not helping anyone by being incomplete

so dont fork and act like you are helping!
